DROP TABLE IF EXISTS TBL_CARS;

CREATE TABLE TBL_CARS (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   brand VARCHAR(250) NOT NULL,
   model VARCHAR(250) NOT NULL,
   VIN VARCHAR(250) NOT NULL,
   colour VARCHAR(250) NOT NULL
);
